# Generated by Django 5.2.7 on 2026-02-21 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='title',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
