# Generated by Django 5.2.7 on 2026-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_trip_is_active_remove_trip_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
