# Generated by Django 5.2.7 on 2026-03-02 12:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trip_price_per_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(db_index=True, default='Kyiv', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=20),
        ),
    ]
