# Generated by Django 5.2.7 on 2026-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trip_city_trip_distance_km_trip_duration_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_summary',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
    ]
