# Generated by Django 5.2.7 on 2026-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_pending_payment', 'Approved pending payment'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
    ]
